# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#

version: '2.3'
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
  # cache:
  #   extends:
  #     file: docker-services.yml
  #     service: cache
  # db:
  #   extends:
  #     file: docker-services.yml
  #     service: db
  # mq:
  #   extends:
  #     file: docker-services.yml
  #     service: mq
  # es:
  #   extends:
  #     file: docker-services.yml
  #     service: es
